In [3]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [2]:
def polynomial_features(X):
    """Takes featurea and polynomial features such that any given pair of features never appears twice as a product"""
    X_poly = np.zeros((X.shape[0], X.shape[1] * (X.shape[1] - 1) // 2)) * np.nan

    # Iterate and store polynomial features
    outer_index = 0
    for index in range(X.shape[1]):
        X_poly[:, outer_index : outer_index + X.shape[1] - index] = (
            X[:, index].reshape(-1, 1) * X[:, index:]
        )
        outer_index += X.shape[1] - index
    return X_poly


def flatten_lower_triangular(matrix):
    """
    Extracts the lower triangular part of the matrix (including the diagonal)
    and returns it as a 1D flattened array.

    Parameters:
        matrix (np.ndarray): A 2D numpy array.

    Returns:
        np.ndarray: A 1D array containing the lower triangular elements of the matrix.
    """
    lower_tri_indices = np.tril_indices_from(matrix)
    return matrix[lower_tri_indices]

In [3]:
df = pd.DataFrame(data=[[2, 3, 4], [7, 6, 5]], columns=["A", "B", "C"])
fit = preprocessing.PolynomialFeatures().fit(df)
transformed = fit.transform(df)
transformed

array([[ 1.,  2.,  3.,  4.,  4.,  6.,  8.,  9., 12., 16.],
       [ 1.,  7.,  6.,  5., 49., 42., 35., 36., 30., 25.]])

In [4]:
np.array([[1.0, 2.0, 3.0, 4.0, 4.0, 6.0, 8.0, 12.0]])

array([[ 1.,  2.,  3.,  4.,  4.,  6.,  8., 12.]])

In [ ]:
a = np.array([[1, 2], [3, 5], [5, 8]])
b = np.array([[4], [2]])


p1 = a @ b
print(p1)

[[ 8]
 [22]
 [36]]
